//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Templates.Views.Welcome {
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class ViewPage1 : RazorEngine.Templating.TemplateBase<Templates.HelloViewModel> {
        
#line hidden
        
        public ViewPage1() {
        }
        
        public override void Execute() {
  
    Layout = "~/Views/Shared/_DefaultLayout.cshtml";

WriteLiteral("\r\n\r\n<p>Hello ");

    Write(Model.FirstName);

WriteLiteral(" ");

                     Write(Model.LastName);

WriteLiteral(" from view page</p>");

        }
    }
}
