//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Templates.Views.Shared {
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class _DefaultLayout : RazorEngine.Templating.TemplateBase<Templates.HelloViewModel> {
        
#line hidden
        
        public _DefaultLayout() {
        }
        
        public override void Execute() {
WriteLiteral("<html>\r\n    <head></head>\r\n    <body>\r\n\r\n        <h1>Hello from layout</h1>\r\n");

WriteLiteral("        ");

   Write(RenderBody());

WriteLiteral("\r\n    </body>\r\n</html>\r\n\r\n");

        }
    }
}
